#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
#bspc config window_gap		15


#Padding
#TILE_PADDING_0 = 50
#TILE_PADDING_1 = 100
#export TILE_PADDING_0
#export TILE_PADDING_1

#Tiled Layout
#bspc config top_padding		50
#bspc config bottom_padding	50
#bspc config left_padding	130	
#bspc config right_padding	130

#Monocle Layout
bspc config top_monocle_padding		3
#bspc config bottom_monocle_padding	-50
#bspc config left_monocle_padding	-130
#bspc config right_monocle_padding	-130



#bspc config split_ratio          0.52
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config single_monocle	true
bspc config automatic_scheme spiral



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
# bspc config focused_border_color        "#6c71c4"
#bspc config focused_border_color        "#8be9fd"
#bspc config focused_border_color        "#2ac3de"
bspc config focused_border_color        "#ffffff"


# bspc config normal_border_color         "#073642"
# bspc config normal_border_color         "#6272a4"
# bspc config normal_border_color         "#ff9e64"


# bspc config active_border_color         "#073642"
bspc config active_border_color         "#8be9fd"


#
# Autostart
#
#
~/.config/autostart/autostart.sh
~/.local/scripts/mvcursor.sh
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Add local script to path
# Bar
#~/.config/polybar/launch.sh &
~/.config/bspwm/polybar/launch.sh &

# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
# picom -CGb &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

picom
